version: '2'

services:
  postgres:
    image: postgres:13.1-alpine
    ports:
      - '5432:5432'
    volumes:
      - '.data/postgres:/var/lib/postgresql/data/'
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
      - POSTGRES_DB=demo
